### ISSUE TITLE
Linux build error

### ISSUE THREAD

**Issue by riyadparvez** [stefanbucur/linux-s2e#2]
I've tried to build using this script: https://github.com/stefanbucur/linux-s2e/blob/master/s2e/build.sh
The following is the error message I'm getting:

Exported revision 22469.
- make -f debian/rules clean
  make -f debian/rules debian/control-real
  make[1]: Entering directory `/home/riyad/src/linux-master/linux-s2e-master'
  chmod +x debian/bin/gencontrol.py
  debian/bin/gencontrol.py
  Traceback (most recent call last):
  File "debian/bin/gencontrol.py", line 427, in <module>
    Gencontrol()()
  File "debian/lib/python/debian_linux/gencontrol.py", line 91, in __call__
    self.do_main(packages, makefile)
  File "debian/lib/python/debian_linux/gencontrol.py", line 111, in do_main
    self.do_main_recurse(packages, makefile, vars, makeflags, extra)
  File "debian/lib/python/debian_linux/gencontrol.py", line 125, in do_main_recurse
    self.do_arch(packages, makefile, arch, vars.copy(), makeflags.copy(), extra)
  File "debian/lib/python/debian_linux/gencontrol.py", line 157, in do_arch
    self.do_arch_packages(packages, makefile, arch, vars, makeflags, extra)
  File "debian/bin/gencontrol.py", line 132, in do_arch_packages
    env=kw_env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
  OSError: [Errno 2] No such file or directory
  make[1]: *** [debian/control-real] Error 1
  make[1]: Leaving directory`/home/riyad/src/linux-master/linux-s2e-master'
  make: **\* [debian/control] Error 2

**Comment by stefanbucur** [comment]
@riyadparvez This script was designed to run in a 32-bit Debootstrap environment for Debian 7 (Wheezy) under Ubuntu. Are you running it in this environment?

**Comment by riyadparvez** [comment]
@stefanbucur Thanks! I didn't realize it has to be run from `chroot`.

Recent 3.x kernels can be built without `chroot` and `deb` packaged without `chroot` or Debootstrap. Is there any other reason you prefer Dbootstrap?

**Comment by stefanbucur** [comment]
I used Debootstrap as I was not able to otherwise build the 32-bit version of the Debian kernel I was interested in on my 64-bit machine. The required 32-bit packages would conflict in the package manager with the 64-bit versions, so I resorted to Debootstrap for an isolated 32-bit package environment.
